[package]
name = "gtk-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.5.5"
glib = "0.16.7"
gdk4 = "0.5.5"
rand = "0.8.5"